networks:
  my_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  database:
    build: ./Db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin1234.
    ports:
      - "1433:1433"
    networks:
      my_network:
        ipv4_address: 172.20.0.2
  backend:
    image: bank-backend-docker
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      my_network:
        ipv4_address: 172.20.0.3